language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t aswilson444/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true aswilson444/react-test npm test

after_success:
  - docker build -t aswilson444/multi-client ./client
  - docker build -t aswilson444/multi-nginx ./nginx
  - docker build -t aswilson444/multi-server ./server
  - docker build -t aswilson444/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push them to dockerhub
  - docker push aswilson444/multi-client
  - docker push aswilson444/multi-nginx
  - docker push aswilson444/multi-server
  - docker push aswilson444/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-893052756509'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access-key-id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY
